### ISSUE TITLE
Open map icon: can it be opened in a new browser?

### ISSUE THREAD

**Issue by markendley** [markendley/enehub#12]
Open map icon: can it be opened in a new browser? This is the right link: https://www.google.com.au/maps/place/15+Blue+St,+North+Sydney+NSW+2060/@-33.8414581,151.2060818,17.75z/data=!4m5!3m4!1s0x6b12aef3753bbfdb:0xec77195e4cb56230!8m2!3d-33.8415142!4d151.2074498

**Comment by ugurcanbulut** [comment]
Done!
